apiVersion: kubeflow.org/v2beta1
kind: MPIJob
metadata:
  name: mpi-perf-4p-nb      # 加入了 -nb 后缀用于区分
spec:
  slotsPerWorker: 1         #
  runPolicy:
    cleanPodPolicy: Running #[cite: 3]
  mpiReplicaSpecs:
    Launcher:
      replicas: 1           #[cite: 3]
      template:
        spec:
          imagePullSecrets:
          - name: default-secret #[cite: 3]
          containers:
          - name: launcher
            image: swr.cn-east-3.myhuaweicloud.com/team43/mpi4py:latest #[cite: 3]
            command:
            - mpirun        #[cite: 3]
            - -n            #[cite: 3]
            - "4"           #[cite: 3]
            - python        #[cite: 3]
            - /opt/mpi/matrix_perf_nonblocking.py  # 修改为非阻塞版本的 Python 脚本
            - --N           #[cite: 3]
            - "1200"        #[cite: 3]
            - --repeat      #[cite: 3]
            - "3"           #[cite: 3]
            volumeMounts:
            - name: code
              mountPath: /opt/mpi/matrix_perf_nonblocking.py  # 修改挂载路径
              subPath: matrix_perf_nonblocking.py             # 修改子路径
          volumes:
          - name: code
            configMap:
              name: matrix-mul-code               # 建议引用新的 ConfigMap
    Worker:
      replicas: 4           #[cite: 3]
      template:
        spec:
          imagePullSecrets:
          - name: default-secret #[cite: 3]
          containers:
          - name: worker
            image: swr.cn-east-3.myhuaweicloud.com/team43/mpi4py:latest #[cite: 3]
            resources:
              requests:
                cpu: "1"    #[cite: 3]
                memory: "1Gi" #[cite: 3]